# Generated by Django 2.2.6 on 2019-12-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='timestamp',
        ),
    ]
